{% set name = "dash-intersection-observer" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dash_intersection_observer-{{ version }}.tar.gz
  sha256: 029f51c00b0f1d7440233b06e9400c0594df41df78b29a119373af5abd25f289

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - dash_intersection_observer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/renaudln/dash_intersection_observer
  summary: Intersection Observer for Dash
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/renaudln/dash_intersection_observer

extra:
  recipe-maintainers:
    - RenaudLN
